version: '2.1'

services:
    #mysql database image creation
    db:
      image: mysql:5.6.17
      container_name: mysql-db  
      environment:
        - MYSQL_ROOT_PASSWORD=spring
      ports:
        - "3306:3306"
      restart: always
      healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10

    
    #notebook Manager app image creation
    notebookservice:
      image: notebook-service
      container_name: notebook-service-app
      build:
        context: .                          # path to docker file
        dockerfile: Dockerfile
      ports:
        - "8090:8080"                       # notebook service port
      restart: always

      depends_on:
         db :
           condition: service_healthy
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/notebook_manager?createDatabaseIfNotExist=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: spring